/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package VendasView;

import ThreadController.ThreadController;
import javax.swing.JButton;

/**
 *
 * @author Guilherme
 */
public class VendasJFrame extends javax.swing.JFrame {

     private ThreadController controller = null;

     
    /**
     * Creates new form VendasJFrame
     */
    public VendasJFrame() {
        initComponents();
        controller = new ThreadController(this);
        controller.runThread();
        setTitle("Venda de Ingressos");
      //  bannerButton.
        
    }
    
    
    public JButton getJbutton(int IdtoRun){
    if (IdtoRun ==0){
        return bannerButton;
        
    }
       return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtextNumero = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        filmeBox = new javax.swing.JComboBox();
        vendaButton = new javax.swing.JButton();
        relatorioButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cadastroButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bannerButton.setBorderPainted(false);
        getContentPane().add(bannerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 493, 69));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Em breve:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 193, 171, 26));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Numero de Ingressos:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jtextNumero.setText("1");
        jtextNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextNumeroActionPerformed(evt);
            }
        });
        getContentPane().add(jtextNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 106, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Sessão :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 41));

        filmeBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        filmeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmeBoxActionPerformed(evt);
            }
        });
        getContentPane().add(filmeBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 214, 36));

        vendaButton.setText("Vender");
        vendaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vendaButtonActionPerformed(evt);
            }
        });
        getContentPane().add(vendaButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 106, 34));

        relatorioButton.setText("Gerar Relatorio de Vendas");
        relatorioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(relatorioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, 44));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Compra de Ingressos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 190, 31));

        cadastroButton.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        cadastroButton.setText("<< Voltar");
        cadastroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastroButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cadastroButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 160, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtextNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextNumeroActionPerformed

    private void filmeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_filmeBoxActionPerformed

    private void vendaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vendaButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vendaButtonActionPerformed

    private void relatorioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relatorioButtonActionPerformed

    private void cadastroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastroButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cadastroButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VendasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VendasJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bannerButton;
    private javax.swing.JButton cadastroButton;
    private javax.swing.JComboBox filmeBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtextNumero;
    private javax.swing.JButton relatorioButton;
    private javax.swing.JButton vendaButton;
    // End of variables declaration//GEN-END:variables



}